config/authapp/urls.py
from django.urls import path
from authapp import views
from authapp.apps import AuthappConfig

app_name = AuthappConfig.name

urlpatterns = [
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", views.CustomLogoutView.as_view(), name="logout"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("profile_edit/", views.ProfileEditView.as_view(), name="profile_edit"),
]

config/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='mainapp')),
    path("authapp/", include("authapp.urls", namespace="authapp")),
    path("social_auth/", include("social_django.urls", namespace="social")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

config/mainapp/urls.py
from django.urls import path
from mainapp import views
from mainapp.apps import MainappConfig


app_name = MainappConfig.name

urlpatterns = [
        path("", views.MainPageView.as_view(), name="main_page"),
        path("news/", views.NewsPageView.as_view(), name="news"),
        path("news/<int:pk>/", views.NewsPageDetailView.as_view(), name="news_detail"),
        path("courses/", views.CoursesListView.as_view(), name="courses"),
        path("courses/<int:pk>/", views.CoursesDetailView.as_view(), name="courses_detail"),
        path("contacts/", views.ContactsPageView.as_view(), name="contacts"),
        path("doc_site/", views.DocSitePageView.as_view(), name="doc_site"),
]

config/mainapp/models.py
from django.db import models


class News(models.Model):
    title = models.CharField(max_length=256, verbose_name="Title")
    preambule = models.CharField(max_length=1024, verbose_name="Preambule")
    body = models.TextField(blank=True, null=True, verbose_name="Body")
    body_as_markdown = models.BooleanField(
        default=False, verbose_name="As markdown"
    )
    created = models.DateTimeField(
        auto_now_add=True, verbose_name="Created", editable=False
    )
    updated = models.DateTimeField(
        auto_now=True, verbose_name="Edited", editable=False
    )
    deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.pk} {self.title}"

    def delete(self, *args):
        self.deleted = True
        self.save()


class Courses(models.Model):
    name = models.CharField(max_length=256, verbose_name="Name")
    description = models.TextField(
        verbose_name="Description", blank=True, null=True
    )
    description_as_markdown = models.BooleanField(
        verbose_name="As markdown", default=False
    )
    cost = models.DecimalField(
        max_digits=8, decimal_places=2, verbose_name="Cost", default=0
    )
    cover = models.CharField(
        max_length=25, default="no_image.svg", verbose_name="Cover"
    )
    created = models.DateTimeField(auto_now_add=True, verbose_name="Created")
    updated = models.DateTimeField(auto_now=True, verbose_name="Edited")
    deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.pk} {self.name}"

    def delete(self, *args):
        self.deleted = True
        self.save()


class Lesson(models.Model):
    course = models.ForeignKey(Courses, on_delete=models.CASCADE)
    num = models.PositiveIntegerField(verbose_name="Lesson number")
    title = models.CharField(max_length=256, verbose_name="Name")
    description = models.TextField(
        verbose_name="Description", blank=True, null=True
    )
    description_as_markdown = models.BooleanField(
        verbose_name="As markdown", default=False
    )
    created = models.DateTimeField(
        auto_now_add=True, verbose_name="Created", editable=False
    )
    updated = models.DateTimeField(
        auto_now=True, verbose_name="Edited", editable=False
    )
    deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.course.name} | {self.num} | {self.title}"

    def delete(self, *args):
        self.deleted = True
        self.save()

    class Meta:
        ordering = ("course", "num")


class CourseTeachers(models.Model):
    course = models.ManyToManyField(Courses)
    name_first = models.CharField(max_length=128, verbose_name="Name")
    name_second = models.CharField(max_length=128, verbose_name="Surname")
    day_birth = models.DateField(verbose_name="Birth date")
    deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return "{0:0>3} {1} {2}".format(
            self.pk, self.name_second, self.name_first
        )

    def delete(self, *args):
        self.deleted = True
        self.save()

config/mainapp/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView
from mainapp import models as mainapp_models


class MainPageView(TemplateView):
    template_name = "mainapp/index.html"


class NewsPageView(TemplateView):
    template_name = "mainapp/news.html"

    def get_context_data(self, **kwargs):
        # Get all previous data
        context = super().get_context_data(**kwargs)
        # Create your own data
        context["news_qs"] = mainapp_models.News.objects.all()[:5]
        return context


class NewsPageDetailView(TemplateView):
    template_name = "mainapp/news_detail.html"

    def get_context_data(self, pk=None, **kwargs):
        context = super().get_context_data(pk=pk, **kwargs)
        context["news_object"] = get_object_or_404(mainapp_models.News, pk=pk)
        return context


class CoursesListView(TemplateView):
    template_name = "mainapp/courses_list.html"

    def get_context_data(self, **kwargs):
        context = super(CoursesListView, self).get_context_data(**kwargs)
        context["objects"] = mainapp_models.Courses.objects.all()[:7]
        return context


class CoursesDetailView(TemplateView):
    template_name = "mainapp/courses_detail.html"

    def get_context_data(self, pk=None, **kwargs):
        context = super(CoursesDetailView, self).get_context_data(**kwargs)
        context["course_object"] = get_object_or_404(
            mainapp_models.Courses, pk=pk
        )
        context["lessons"] = mainapp_models.Lesson.objects.filter(
            course=context["course_object"]
        )
        context["teachers"] = mainapp_models.CourseTeachers.objects.filter(
            course=context["course_object"]
        )
        return context


class ContactsPageView(TemplateView):
    template_name = "mainapp/contacts.html"


class DocSitePageView(TemplateView):
    template_name = "mainapp/doc_site.html"

config/mainapp/templates/mainapp/base.html
{% load static %}

<!doctype html>
<html lang="ru">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport"
    content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

  <!-- ChartJS -->
  <link rel="stylesheet" href="{% static 'css/Chart.min.css' %}">

  <!-- FontAwesome -->
  <link rel="stylesheet" href="{% static 'css/fontawesome.all.min.css' %}">

  <title>
    {% block title %}
    Welcome to Braniac!
    {% endblock title %}
  </title>
</head>

<body>

  {% include 'includes/main_menu.html' %}

  {% block messages %}
  {% include 'includes/messages.html' %}
  {% endblock messages %}

  <div class="container-md">

    {% block content %}

    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur
    optio est esse? Veritatis laborum expedita
    quibusdam numquam! Expedita amet nisi dolor similique autem, mollitia
    ipsa et, natus vel explicabo
    reprehenderit?

    {% endblock content %}

  </div>

  <!-- Footer -->

  <div class="container-lg mt-auto">
    <hr>
    <div class="row justify-content-center">
      <div class="col-sm-6 col-md-3 text-center">
        <p>
          <strong>Braniac</strong>
        </p>
        <p>
        <ul class="list-unstyled">
          <li><a href="{% url 'mainapp:main_page' %}">Домашняя</a></li>
          <li><a href="{% url 'mainapp:news' %}">Новости</a></li>
          {% if user.is_authenticated %}
          <li><a href="{% url 'authapp:logout' %}">Выйти</a></li>
          {% else %}
          <li><a href="{% url 'authapp:login' %}">Войти</a></li>
          {% endif %}
        </ul>
        </p>
      </div>
      <div class="col-sm-6 col-md-3 text-center">
        <p>
          <strong>Полезное</strong>
        </p>
        <p>
        <ul class="list-unstyled">
          <li><a href="#">Положения &amp; Условия</a></li>
          <li><a href="#">Конфиденциальность &amp; Cookies</a></li>
          <li><a href="#">Документация по API</a></li>
          <li><a href="{% url 'mainapp:doc_site' %}">Документация по сайту</a>
          </li>
        </ul>
        </p>
      </div>
      <div class="col-sm-6 col-md-3 text-center">
        <p>
          <strong>Мы в социальных сетях</strong>
        </p>
        <p>
        <div class="row justify-content-around">
          <div><a href="#"><i class="fab fa-vk fa-2x"></i></a></div>
          <div><a href="#"><i class="fab fa-facebook-f fa-2x"></i></a>
          </div>
          <div><a href="#"><i class="fab fa-instagram fa-2x"></i></a>
          </div>
          <div><a href="#"><i class="fab fa-pinterest-p fa-2x"></i></a></div>
        </div>
        </p>
        <p>
          <strong>Наше приложение</strong>
        </p>
        <p>
        <div class="row justify-content-around">
          <div><a href="#"><i class="fab fa-app-store fa-2x"></i></a>
          </div>
          <div><a href="#"><i class="fab fa-google-play fa-2x"></i></a></div>
          <div><a href="#"><i class="fab fa-windows fa-2x"></i></a>
          </div>
        </div>
        </p>
      </div>
    </div>
    <div class="row justify-content-center">
      <div>
        <p><small>&copy; GeekBrains 2021</small></p>
      </div>
    </div>
  </div>

  <!-- /Footer -->




  <!-- JavaScript section -->
  <!-- Bootstrap -->
  <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>

  <!-- ChartJs -->
  <script src="{% static 'js/Chart.min.js' %}"></script>

  <!-- FontAwesome -->
  <script src="{% static 'js/fontawesome.all.min.js' %}"></script>

  {% block js %}
  <script>
    $(document).ready(function () {

      {% if messages %}
      // Toasts
      $(".toast").toast({ delay: 5000 });
      $(".toast").toast("show");
      {% endif %}

    });
  </script>
  {% endblock js %}

</body>

</html>

config/mainapp/templates/mainapp/contacts.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load email_to_link %}


{% block content %}
    <div class="container-md">

        <p>
        <div class="jumbotron jumbotron-fluid">
          <div class="container">
            <h1 class="display-4">Наши контакты</h1>
            <p class="lead">Обязательно свяжитесь с нами! Ваш комфорт - наша забота.</p>
          </div>
        </div>
        </p>
        <p>
        <div class="row justify-content-around mt-n2">
          
          <div class="col-sm-6 col-md-6 col-lg-4 pb-2">
            <div class="card h-100 shadow">
              <div class="card-body">
                <div style="position:relative;overflow:hidden;"><a href="https://yandex.ru/maps/org/petropavlovskaya_krepost/146720535721/?utm_medium=mapframe&utm_source=maps"                 style="color:#eee;font-size:12px;position:absolute;top:0px;">Петропавловская крепость</a><a                 href="https://yandex.ru/maps/2/saint-petersburg/category/landmark_attraction/89683368508/?utm_medium=mapframe&utm_source=maps"                 style="color:#eee;font-size:12px;position:absolute;top:14px;">Достопримечательность в                 Санкт‑Петербурге</a><a                 href="https://yandex.ru/maps/2/saint-petersburg/category/museum/184105894/?utm_medium=mapframe&utm_source=maps"                 style="color:#eee;font-size:12px;position:absolute;top:28px;">Музей в Санкт‑Петербурге</a><iframe                 src="https://yandex.ru/map-widget/v1/-/CCUAZHcrhA" width="100%" height="300" frameborder="0"                 allowfullscreen="true" style="position:relative; border-radius: 4px;"></iframe>             </div>
                <h5 class="card-title">Санкт‑Петербург</h5>
                <p class="card-text">
                <ul class="list-unstyled">
                  <li>Телефон</li>
                  <li><strong>+7-999-11-11111</strong></li>
                </ul>
                <ul class="list-unstyled">
                  <li>Email</li>
                  <li><strong>{{ 'geeklab@spb.ru'|email_to_link }}</strong></li>
                </ul>
                <ul class="list-unstyled">
                  <li>Адрес</li>
                  <li><strong>территория Петропавловская крепость, 3Ж</strong></li>
                </ul>
                </p>
              </div>
            </div>
          </div>
          
          <div class="col-sm-6 col-md-6 col-lg-4 pb-2">
            <div class="card h-100 shadow">
              <div class="card-body">
                <div style="position:relative;overflow:hidden;"><a href="https://yandex.ru/maps/org/kazanskiy_kreml/95813866834/?utm_medium=mapframe&utm_source=maps"                 style="color:#eee;font-size:12px;position:absolute;top:0px;">Казанский Кремль</a><a                 href="https://yandex.ru/maps/43/kazan/category/museum/184105894/?utm_medium=mapframe&utm_source=maps"                 style="color:#eee;font-size:12px;position:absolute;top:14px;">Музей в Казани</a><a                 href="https://yandex.ru/maps/43/kazan/category/landmark_attraction/89683368508/?utm_medium=mapframe&utm_source=maps"                 style="color:#eee;font-size:12px;position:absolute;top:28px;">Достопримечательность в Казани</a><iframe                 src="https://yandex.ru/map-widget/v1/-/CCUAZHX3xB" width="100%" height="300" frameborder="0"                 allowfullscreen="true" style="position:relative; border-radius: 4px;"></iframe>             </div>
                <h5 class="card-title">Казань</h5>
                <p class="card-text">
                <ul class="list-unstyled">
                  <li>Телефон</li>
                  <li><strong>+7-999-22-22222</strong></li>
                </ul>
                <ul class="list-unstyled">
                  <li>Email</li>
                  <li><strong>{{'geeklab@kz.ru'|email_to_link}}</strong></li>
                </ul>
                <ul class="list-unstyled">
                  <li>Адрес</li>
                  <li><strong>территория Кремль, 11, Казань, Республика Татарстан, Россия</strong></li>
                </ul>
                </p>
              </div>
            </div>
          </div>
          
          <div class="col-sm-6 col-md-6 col-lg-4 pb-2">
            <div class="card h-100 shadow">
              <div class="card-body">
                <div style="position:relative;overflow:hidden;"><a href="https://yandex.ru/maps/org/sobor_pokrova_presvyatoy_bogoroditsy_na_rvu/175159255687/?utm_medium=mapframe&utm_source=maps"                 style="color:#eee;font-size:12px;position:absolute;top:0px;">Собор Покрова Пресвятой Богородицы на                 Рву</a><a href="https://yandex.ru/maps/213/moscow/category/museum/184105894/?utm_medium=mapframe&utm_source=maps"                 style="color:#eee;font-size:12px;position:absolute;top:14px;">Музей в Москве</a><iframe                 src="https://yandex.ru/map-widget/v1/-/CCUAZHh9kD" width="100%" height="300" frameborder="0"                 allowfullscreen="true" style="position:relative; border-radius: 4px;"></iframe>             </div>
                <h5 class="card-title">Москва</h5>
                <p class="card-text">
                <ul class="list-unstyled">
                  <li>Телефон</li>
                  <li><strong>+7-999-33-33333</strong></li>
                </ul>
                <ul class="list-unstyled">
                  <li>Email</li>
                  <li><strong>{{'geeklab@msk.ru'|email_to_link }}</strong></li>
                </ul>
                <ul class="list-unstyled">
                  <li>Адрес</li>
                  <li><strong>Красная площадь, 7, Москва, Россия</strong></li>
                </ul>
                </p>
              </div>
            </div>
          </div>
          
        </div>
        </p>



    </div>

    {% endblock %}

config/mainapp/templates/mainapp/courses_list.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
    <div class="container-md">

        
    <div class="row justify-content-center mt-3">
        

                <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
                <a href="#">
                    <img src="{% static '/img/course001.jpg' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title text-center">Web Python</h5>
                    </div>
                </a>
                </div>

        

                <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
                <a href="#">
                    <img src="{% static '/img/course002.jpg' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title text-center">Web Golang</h5>
                    </div>
                </a>
                </div>

        

                <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
                <a href="#">
                    <img src="{% static '/img/course003.jpg' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title text-center">Web JavaScript</h5>
                    </div>
                </a>
                </div>

        

                <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
                <a href="#">
                    <img src="{% static '/img/course004.jpg' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title text-center">Web Java</h5>
                    </div>
                </a>
                </div>

        

                <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
                <a href="#">
                    <img src="{% static '/img/course005.jpg' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title text-center">Web PHP</h5>
                    </div>
                </a>
                </div>

        

                <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
                <a href="#">
                    <img src="{% static '/img/course006.jpg' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title text-center">Python AI</h5>
                    </div>
                </a>
                </div>

        

                <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
                <a href="#">
                    <img src="{% static '/img/course007.jpg' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title text-center">DevOps</h5>
                    </div>
                </a>
                </div>

        
    </div>
    <div class="row justify-content-center align-items-center mt-3 mb-n3">
  <nav aria-label="Page navigation example">
    <ul class="pagination">
      <li class="page-item"><a class="page-link" href="#">Previous</a></li>
      <li class="page-item"><a class="page-link" href="#">1</a></li>
      <li class="page-item"><a class="page-link" href="#">2</a></li>
      <li class="page-item"><a class="page-link" href="#">3</a></li>
      <li class="page-item"><a class="page-link" href="#">Next</a></li>
    </ul>
  </nav>
</div>


    </div>

{% endblock %}

config/mainapp/templates/mainapp/doc_site.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
<div class="container-md">

        
<div class="row justify-content-center align-items-center mt-3">
  <div class="col-md-9">
    <div class="card">
      <div class="card-header">
        Документация по сайту
      </div>
      <div class="card-body">

        <h5 class="card-title">CSS-стили</h5>
        <p class="card-text">
        <ul>
          <li><a href="https://getbootstrap.com/docs/4.6/getting-started/introduction/" target="_blank">Bootstrap
              v4.6</a></li>
          <li><a href="https://bootswatch.com/lumen/" target="_blank">Bootstrap theme: Lumen</a></li>
        </ul>
        </p>

        <h5 class="card-title">Иконки</h5>
        <p class="card-text">
          <a href="https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use">FontAwesome 5.15.3</a>
        </p>

        <h5 class="card-title">Графики</h5>
        <p class="card-text">
          <a href="https://www.chartjs.org/">ChartJS</a>
        </p>

        <h5 class="card-title">Графика</h5>
        <p class="card-text">
        <ul>
          <li><a href="https://www5.flamingtext.com/" target="_blank" rel="noopener noreferrer">Логотип by
              flamingtext.com</a></li>
          <li><a href="https://www.pexels.com/ru-ru" target="_blank" rel="noopener noreferrer">Фотографии by
              pexels.com</a>. Все изображения распространяются под бесплатной лицензией. Для страницы обзоров фотографии
            должны быть с соотношением сторон кратным 2.912 (например, 1920x659)</li>
          <li><a href="https://getavataaars.com/" target="_blank" rel="noopener noreferrer">Аватарки пользователей by
              getavataaars.com</a></li>
        </ul>
        </p>

      </div>
    </div>
  </div>
</div>


    </div>

{% endblock %}

config/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
    <div class="container-md">

        

    <div id="carouselExampleIndicators" class="carousel slide carousel-fade" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner" style="background-color: #777; font-size: 1.25rem;">
            <div class="carousel-item active">
                <img src="{% static '/img/slider001.jpg' %}" class="d-block w-100" alt="" style="opacity: 0.3;">
                <div class="carousel-caption d-none d-md-block">
                    <h3>Будь продуктивным</h3>
                    <p>Изучай только актуальные тренды современного IT</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static '/img/slider002.jpg' %}" class="d-block w-100" alt="" style="opacity: 0.3;">
                <div class="carousel-caption d-none d-md-block">
                    <h3>Учись где угодно</h3>
                    <p>Парк, библиотека или дома под тёплым пледом - выбирай время и место учёбы сам</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static '/img/slider003.jpg' %}" class="d-block w-100" alt="" style="opacity: 0.3;">
                <div class="carousel-caption d-none d-md-block">
                    <h3>Braniac - это МЫ</h3>
                    <p>Вливайся в нашу IT-тусовку - нас уже более 5000 брайниаков</p>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

    <div class="jumbotron">
        <h1 class="display-4">Приветствую, путник!</h1>
        <p class="lead">
            На данном портале мы собрали сообщество людей объединённых одной целью - получать знания! В современном мире
            уже сложно представить человека не общающегося с компьютером. Повсеместное проникновение интернета дало
            возможность объеденить людей и сделать знания доступными как никогда ранее. У тебя есть уникальная
            возможность получить актуальные знания используя современные технологии. Не упусти свой шанс и переходи на
            вкладку "Курсы", записывайся на курсы и становись востребованным специалистом.
        </p>
    </div>

    <h3>Отзывы участников сообщества</h3>


    <div class="row text-center">

        
            <div class="col-lg-4">
                <img src="{% static '/img/user001.png' %}" alt="" style="max-width: 140px;">
                <h2>Лера</h2>
                <p>Выучила Python и получаю 300кк в секунду! Спасибо Браниаку!</p>
            </div>
        
            <div class="col-lg-4">
                <img src="{% static '/img/user002.png' %}" alt="" style="max-width: 140px;">
                <h2>Антоша</h2>
                <p>Больше не туплю в excel - только БД только хардкор!</p>
            </div>
        
            <div class="col-lg-4">
                <img src="{% static '/img/user003.png' %}" alt="" style="max-width: 140px;">
                <h2>Леонард</h2>
                <p>Как пропатчить KDE под FreeBSD?!</p>
            </div>
        

    </div>

    <div class="my-5">
        <hr>
    </div>

    <div class="row justify-content-center align-items-center">
        <div class="col-md-7">
            <h1>Сотни готовых курсов от лучших авторов</h1>
            <p>Выбирай из огромной коллекции готовых решений для самообразования</p>
        </div>
        <div class="col-md-5">
            <img src="{% static '/img/promo001.jpg' %}" alt="" class="w-100 h-100 rounded" style="opacity: 0.7;">
        </div>
    </div>

    <div class="my-5">
        <hr>
    </div>

    <div class="row justify-content-center align-items-center">
        <div class="col-md-5">
            <img src="{% static '/img/promo002.jpg' %}" alt="" class="w-100 h-100 rounded" style="opacity: 0.7;">
        </div>
        <div class="col-md-7">
            <h1>Монетизируй знания</h1>
            <p>Эксперт в свой области - давай к нам! Выгодные условия для тебя и пользователи со всего мира на нашей
                платформы</p>
        </div>
    </div>

    <div class="my-5">
        <hr>
    </div>

    <div class="row justify-content-center align-items-center">
        <div class="col-md-7">
            <h1>Вместе мы сила</h1>
            <p>Проекты любой сложности становятся легче, если ты в компании единомышленников. Присоединяйся!</p>
        </div>
        <div class="col-md-5">
            <img src="{% static '/img/promo003.jpg' %}" alt="" class="w-100 h-100 rounded" style="opacity: 0.7;">
        </div>
    </div>


    </div>

    {% endblock %}

config/mainapp/templates/mainapp/news.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
<div class="container-md">

<div class="row">

  <div class="col-lg-8">
    {% for _ in range %}
    <div class="card my-2">
      <div class="card-body">
        <h5 class="card-title">Новость</h5>
        <h6 class="card-subtitle mb-2 text-muted">2021-04-29 20-50-26</h6>
        <p class="card-text">Предварительное описание новости</p>
        <a href="#" class="card-link">Подробнее</a>
      </div>
    </div>
    {% endfor %}

  </div>

  <div class="col-lg-4">
    <div class="card my-2 sticky-top">
      <div class="card-header">
        Фильтры
      </div>
      <div class="card-body">
        <form action="">
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon1">Дата от...</span>
            </div>
            <input type="date" class="form-control" name="dateFrom">
          </div>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon1">Дата до...</span>
            </div>
            <input type="date" class="form-control" name="dateTo">
          </div>

          <button type="submit" class="btn btn-primary btn-block">Фильтровать</button>
        </form>
      </div>
    </div>
  </div>

</div>

<div class="row justify-content-center align-items-center mt-3 mb-n3">
  <nav aria-label="Page navigation example">
    <ul class="pagination">
      <li class="page-item"><a class="page-link" href="#">Previous</a></li>
      <li class="page-item"><a class="page-link" href="#">1</a></li>
      <li class="page-item"><a class="page-link" href="#">2</a></li>
      <li class="page-item"><a class="page-link" href="#">3</a></li>
      <li class="page-item"><a class="page-link" href="#">Next</a></li>
    </ul>
  </nav>
</div>

</div>

{% endblock %}